packaging_format = 2

id = "fluxbb"
name = "FluxBB"
description.en = "Fast, light, user-friendly forum software"
description.fr = "Forum de discussions rapide et léger"

version = "1.5.12~ynh1"

maintainers = ["Antoine"]

[upstream]
license = "GPL-2.0-only"
website = "https://fluxbb.org/"
demo = "https://fluxbb.org/forums/index.php"
admindoc = "https://fluxbb.org/docs/"
code = "https://github.com/fluxbb/fluxbb/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/fluxbb"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/fluxbb/fluxbb/archive/refs/tags/fluxbb-1.4.12.tar.gz"
        sha256 = "c0bb70979f80576f2b078a736cd7b0b7f3dee891006c07f7cfb66ca2ac6d0162"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-fpm"

    [resources.database]
    type = "mysql"
