#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_upload_max_filesize --value=256M
ynh_app_setting_set --key=php_memory_limit --value=256M

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

email=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated nginx config
ynh_config_add_nginx

# Create a dedicated php-fpm config
ynh_config_add_phpfpm

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
#ynh_script_progression "Setting up application with CURL..."

# Installation with cURL
#ynh_local_curl "/install.php?submit" "install_lang=French" "req_db_type=mysqli_innodb" "req_db_host=localhost" "req_db_name=$db_name" "db_username=$db_user" "db_password=$db_pwd" "db_prefix=fl_" "req_username=$admin" "req_password1=$password" "req_password2=$password" "req_email=$email" "req_title=YunoFluxBB" "desc=FluxBB_package_for_Yunohost" "req_base_url=https://$domain$path"  "req_default_lang=French" "req_default_style=Air"

#ynh_safe_rm "$install_dir/install.php"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
